import type { TermoDicionario } from './types';

export const BASE_TERMOS_DICIONARIO: TermoDicionario[] = [
  // --- M1: FUNDAMENTOS & TEORIA DA INFORMAÇÃO ---
  {
    id: 'documentacao',
    termo: 'Documentação (Paul Otlet & Teoria Documental)',
    sinonimos: ['documentacao', 'documentacao geral', 'teoria da documentacao', 'conceito de documentacao', 'paul otlet documentacao', 'tratado de documentacao'],
    area: 'Fundamentos da Ciência da Informação e Documentação',
    moduloRelacionado: 'M1',
    conceitoCanonico: 'Disciplina e técnica fundada por Paul Otlet e Henri La Fontaine no final do século XIX (criação do Instituto Internacional de Bibliografia - IIB em 1895, posterior FID), consagrada no histórico "Traité de Documentation" (1934). Diferencia-se da Biblioteconomia tradicional por superar a restrição exclusiva ao livro encadernado, estendendo-se a qualquer suporte ou vestígio material portador de informação registrada (artigos de periódicos, relatórios técnicos, fotografias, patentes, mapas), com ênfase primordial na análise de conteúdo minuciosa, síntese e disseminação ativa. Em 1951, Suzanne Briet consolidou a teoria clássica com a obra "Qu\'est-ce que le document?", conceituando documento como qualquer índice ou indício corpóreo fixado para fins de prova, consulta ou testemunho.',
    armadilhaCebraspe: 'O Cebraspe tenta com frequência restringir a Documentação à guarda física e passiva de papéis ou considerá-la sinônimo estrito da Biblioteconomia tradicional. ERRADO: para o Cebraspe, a Documentação se distingue pela universalidade dos suportes (não apenas livros), pelo tratamento analítico minucioso (partes de obras e artigos) e pela disseminação dinâmica e proativa.',
    aplicacaoCamara: 'No Centro de Documentação e Informação (CEDI) da Câmara dos Deputados, a gestão e indexação das notas taquigráficas de plenário, arquivos em áudio e vídeo de CPIs, pareceres e projetos de lei em múltiplos formatos corporificam os preceitos clássicos da Documentação.',
    fonteReferencia: 'OTLET, Paul. Traité de Documentation. Bruxelles: Mundaneum, 1934; BRIET, Suzanne. Qu\'est-ce que le document?. Paris: EDIT, 1951.',
  },
  {
    id: 'paul-otlet',
    termo: 'Paul Otlet e o Mundaneum (Pai da Documentação & CDU)',
    sinonimos: ['paul otlet', 'otlet', 'mundaneum', 'iib', 'fid', 'pai da documentacao', 'repertoire bibliographique universel'],
    area: 'História e Epistemologia da Ciência da Informação',
    moduloRelacionado: 'M1',
    conceitoCanonico: 'Paul Otlet (1868–1944), jurista e bibliógrafo belga, é considerado o pai da Documentação e um dos maiores visionários precursores da Ciência da Informação e da internet. Fundou em 1895, com Henri La Fontaine, o Instituto Internacional de Bibliografia (IIB), adaptou e expandiu a Classificação Decimal de Dewey (CDD) para criar a Classificação Decimal Universal (CDU), padronizou a ficha bibliográfica de 7,5 x 12,5 cm e concebeu o Mundaneum (cidade mundial do saber com o Repertório Bibliográfico Universal, reunindo mais de 15 milhões de fichas interconectadas).',
    armadilhaCebraspe: 'A banca costuma atribuir a criação da CDU exclusivamente a Melvil Dewey ou afirmar que Otlet lidava apenas com bibliotecas tradicionais. Melvil Dewey criou a CDD (1876); Otlet e La Fontaine criaram a CDU (1905) e fundaram o movimento documentalista.',
    aplicacaoCamara: 'A Biblioteca da Câmara dos Deputados adota a CDU — desenvolvida pioneiramente por Otlet — na classificação sistemática de todo o seu acervo de Direito Constitucional, Ciência Política e Legislação.',
    fonteReferencia: 'OTLET, Paul. Traité de Documentation: le livre sur le livre, théorie et pratique. Bruxelles: Mundaneum, 1934.',
  },
  {
    id: 'informacao-como-coisa',
    termo: 'Informação como Coisa (Information as Thing)',
    sinonimos: ['informação-como-coisa', 'buckland coisa', 'information as thing'],
    area: 'Fundamentos da Ciência da Informação',
    moduloRelacionado: 'M1',
    conceitoCanonico: 'Conceito formulado por Michael Buckland (1991) para designar a informação corporificada em suportes físicos, tangíveis ou digitais (dados, textos, documentos, objetos e artefatos). Diferencia-se da informação-como-processo (o ato de ser informado) e da informação-como-conhecimento (o saber subjetivo intangível gravado na mente do indivíduo).',
    armadilhaCebraspe: 'O Cebraspe tenta restringir a informação-como-coisa apenas a livros impressos ou textos verbais, excluindo objetos tridimensionais, amostras minerais ou artefatos de museu. Lembre-se: qualquer objeto físico passível de transmitir evidência é informação-como-coisa.',
    aplicacaoCamara: 'Na Biblioteca da Câmara e no Centro de Documentação e Informação (CEDI), os anais históricos, fitas magnéticas de sessões deliberativas e objetos museológicos do Palácio do Congresso operam ontologicamente como informação-como-coisa.',
    fonteReferencia: 'BUCKLAND, Michael. Information and Information Systems. New York: Greenwood Press, 1991.',
  },
  {
    id: 'antelope-de-briet',
    termo: 'O Antílope de Briet (Teoria do Documento)',
    sinonimos: ['briet', 'suzanne briet', 'antelope', 'o que e um documento'],
    area: 'Fundamentos da Ciência da Informação',
    moduloRelacionado: 'M1',
    conceitoCanonico: 'Postulado clássico de Suzanne Briet (1951, "Qu\'est-ce que le document?"): um antílope correndo livre na savana não é um documento; contudo, a partir do momento em que é capturado, enjaulado em um zoológico, catalogado e submetido à observação científica, ele torna-se um documento primário (uma evidência física portadora de informação).',
    armadilhaCebraspe: 'A banca afirma que para Briet qualquer objeto natural é um documento em seu estado bruto original. Falso! É indispensável a intencionalidade humana de fixação, custódia e uso como testemunho ou prova científica.',
    aplicacaoCamara: 'Um discurso solto de um deputado em plenário só se converte em documento arquivístico/bibliográfico oficial quando é degravado, revisado pelas notas taquigráficas e incorporado aos anais da Casa.',
    fonteReferencia: 'BRIET, Suzanne. Qu\'est-ce que le document?. Paris: EDIT, 1951.',
  },
  {
    id: 'paradigmas-de-capurro',
    termo: 'Paradigmas da Ciência da Informação (Capurro)',
    sinonimos: ['paradigmas capurro', 'paradigma fisico', 'paradigma cognitivo', 'paradigma social'],
    area: 'Epistemologia da Ciência da Informação',
    moduloRelacionado: 'M1',
    conceitoCanonico: 'Sistematização epistemológica de Rafael Capurro (2003) que divide a evolução da CI em três grandes paradigmas: (1) Físico (foco na transmissão de sinais e no documento como entidade física estática - Shannon & Weaver); (2) Cognitivo (foco nos estados mentais e na alteração de estruturas cognitivas do usuário - Brookes e Belkin); e (3) Social/Hermenêutico (foco na informação como prática social situada em comunidades de discurso e domínios - Hjørland).',
    armadilhaCebraspe: 'Trocar as definições entre os paradigmas ou afirmar que o paradigma social substituiu e eliminou os anteriores, quando na verdade eles coexistem em complementaridade.',
    aplicacaoCamara: 'A análise de necessidades informacionais das comissões temáticas da Câmara dos Deputados adota o paradigma social/análise de domínio, reconhecendo o jargão e a cultura discursiva dos consultores legislativos.',
    fonteReferencia: 'CAPURRO, Rafael. Epistemologia e Ciência da Informação. ENANCIB, 2003.',
  },
  {
    id: 'cinco-leis-ranganathan',
    termo: 'Cinco Leis da Biblioteconomia (Ranganathan)',
    sinonimos: ['leis de ranganathan', 'ranganathan', 'leis biblioteconomia'],
    area: 'Fundamentos da Biblioteconomia',
    moduloRelacionado: 'M1',
    conceitoCanonico: 'Princípios filosóficos fundamentais enunciados por Shiyali Ramamrita Ranganathan em 1931: (1) Os livros são para usar; (2) A cada leitor o seu livro; (3) A cada livro o seu leitor; (4) Poupe o tempo do leitor; (5) A biblioteca é um organismo em crescimento.',
    armadilhaCebraspe: 'Inversão da 2ª Lei ("a cada leitor o seu livro" - foco na universalização democrática do acesso a todos os públicos) com a 3ª Lei ("a cada livro o seu leitor" - foco no processamento técnico e divulgação para que todo documento encontre seu usuário).',
    aplicacaoCamara: 'A automação dos sistemas de busca do Portal da Câmara e da Biblioteca Pedro Aleixo atende diretamente à 4ª Lei ("Poupe o tempo do leitor/parlamentar").',
    fonteReferencia: 'RANGANATHAN, S. R. The Five Laws of Library Science. Madras: Madras Library Association, 1931.',
  },

  // --- M2: CATALOGAÇÃO & METADADOS ---
  {
    id: 'rvbi-catalogacao-cooperativa',
    termo: 'Rede Virtual de Bibliotecas (RVBI) e Catalogação Cooperativa',
    sinonimos: ['rvbi', 'rede virtual de bibliotecas', 'catalogacao cooperativa', 'rede biblio', 'rede do congresso'],
    area: 'Catalogação e Redes Cooperativas',
    moduloRelacionado: 'M2',
    conceitoCanonico: 'Rede cooperativa de bibliotecas do Poder Legislativo e da Administração Pública Federal brasileira, coordenada pelo Senado Federal e integrada pela Biblioteca Pedro Aleixo da Câmara dos Deputados, STF, STJ, TST, TCU e ministérios. Funciona sob o princípio da catalogação compartilhada com base bibliográfica unificada em formato MARC 21: o registro catalográfico criado por uma biblioteca associada fica instantaneamente disponível para todas as demais, padronizando cabeçalhos de autoridade e termos do Vocabulário Controlado Básico (VCB).',
    armadilhaCebraspe: 'Afirmar que na RVBI cada biblioteca mantém uma base de dados isolada sem compartilhamento de autoridades ou atribuir a coordenação da rede à Biblioteca Nacional. A coordenação executiva e técnica da RVBI é de responsabilidade do Senado Federal.',
    aplicacaoCamara: 'A Biblioteca da Câmara dos Deputados alimenta e usufrui diariamente da RVBI, registrando monografias, periódicos e atos parlamentares para consulta pública integrada.',
    fonteReferencia: 'SENADO FEDERAL. Manual da Rede Virtual de Bibliotecas - RVBI. Brasília: Secretaria de Biblioteca, 2023.',
  },
  {
    id: 'rda',
    termo: 'RDA (Resource Description and Access)',
    sinonimos: ['rda', 'resource description and access', 'padrao rda'],
    area: 'Catalogação e Metadados',
    moduloRelacionado: 'M2',
    conceitoCanonico: 'Padrão internacional de conteúdo para descrição e acesso a recursos, projetado para o ambiente digital e Web Semântica. Substituiu o AACR2r ao fundamentar-se diretamente nos modelos conceituais da família FRBR e no IFLA LRM, abandonando a rigidez do suporte físico.',
    armadilhaCebraspe: 'Afirmar que o RDA substituiu o formato MARC 21. Errado! O RDA é um código de CONTEÚDO (o que registrar), enquanto o MARC 21 é um formato de ESTRUTURA/CODIFICAÇÃO (onde guardar as tags). Os registros RDA são perfeitamente codificados no MARC 21.',
    aplicacaoCamara: 'A Biblioteca Pedro Aleixo cataloga e-books, vídeos de audiências públicas e podcasts legislativos utilizando os campos RDA para interoperabilidade com o catálogo da Rede Virtual de Bibliotecas (RVBI).',
    fonteReferencia: 'RDA STEERING COMMITTEE. RDA Toolkit: Resource Description and Access, 2010/2020.',
  },
  {
    id: 'ifla-lrm',
    termo: 'IFLA LRM (Library Reference Model)',
    sinonimos: ['ifla lrm', 'lrm', 'modelo lrm', 'library reference model'],
    area: 'Catalogação e Modelos Conceituais',
    moduloRelacionado: 'M2',
    conceitoCanonico: 'Modelo conceitual de referência de nível superior desenvolvido pela IFLA e aprovado em 2017. Consolida e unifica em um único arcabouço entidade-relacionamento os três modelos anteriores da IFLA: FRBR (dados bibliográficos), FRAD (dados de autoridade) e FRSAD (dados de assunto).',
    armadilhaCebraspe: 'Afirmar que o IFLA LRM manteve as entidades do FRBR inalteradas. Na verdade, o LRM introduziu uma entidade suprema chamada "Res" (Coisa - tudo o que pode ser objeto de discurso) e unificou Pessoa e Entidade Coletiva sob a superentidade "Agente".',
    aplicacaoCamara: 'Permite modelar o processo legislativo como um grafo de conhecimento onde a "Obra" (a ideia da lei) tem como "Expressão" o texto promulgado e como "Agente" a Câmara dos Deputados.',
    fonteReferencia: 'RIVA, Pat; LE BŒUF, Patrick; ŽUMER, Maja. IFLA Library Reference Model. The Hague: IFLA, 2017.',
  },
  {
    id: 'entidades-wemi',
    termo: 'Entidades WEMI (FRBR / IFLA LRM)',
    sinonimos: ['wemi', 'frbr grupo 1', 'obra expressao manifestacao item'],
    area: 'Catalogação e Modelos Conceituais',
    moduloRelacionado: 'M2',
    conceitoCanonico: 'As quatro entidades do Grupo 1 dos FRBR que representam os aspectos da produção intelectual: (1) Obra (Work) - criação intelectual ou artística abstrata; (2) Expressão (Expression) - a realização intelectual/artística da obra em forma alfanumérica, sonora ou gráfica; (3) Manifestação (Manifestation) - a materialização física ou digital da expressão em um conjunto de exemplares (publicação); (4) Item (Item) - o exemplar físico individualizado ou cópia digital única.',
    armadilhaCebraspe: 'Confundir Expressão com Manifestação (ex.: dizer que a tradução de um livro é uma nova Manifestação, quando na verdade é uma nova Expressão intelectual da mesma Obra).',
    aplicacaoCamara: 'Obra: Constituição Federal de 1988; Expressão: Texto em inglês da CF/88 traduzido pelo Senado; Manifestação: Edição impressa pela Edições Câmara em 2024; Item: O exemplar físico com carimbo tombado na estante da Biblioteca.',
    fonteReferencia: 'IFLA. Functional Requirements for Bibliographic Records: Final Report. München: K.G. Saur, 1998.',
  },
  {
    id: 'dgm-marc',
    termo: 'Designação Geral do Material (DGM) vs. Trio RDA (336/337/338)',
    sinonimos: ['dgm', 'designacao geral do material', 'campos 336 337 338'],
    area: 'Catalogação e Metadados',
    moduloRelacionado: 'M2',
    conceitoCanonico: 'A DGM era o termo entre colchetes utilizado no AACR2r logo após o título principal (campo 245 $h do MARC 21, ex.: [recurso eletrônico]). O padrão RDA extinguiu a DGM e desmembrou a identificação do recurso em três atributos analíticos: Tipo de Conteúdo (MARC 336), Tipo de Mídia (MARC 337) e Tipo de Suporte (MARC 338).',
    armadilhaCebraspe: 'A banca elabora assertivas dizendo que a DGM continua obrigatória no RDA ou que os campos 336/337/338 são usados no AACR2r original. Ambas falsas!',
    aplicacaoCamara: 'Para um parecer legislativo em PDF baixado da internet: Campo 336 = texto; Campo 337 = computador; Campo 338 = recurso online.',
    fonteReferencia: 'LIBRARY OF CONGRESS. MARC 21 Format for Bibliographic Data. Washington, D.C., 2024.',
  },
  {
    id: 'dublin-core',
    termo: 'Padrão Dublin Core (DC)',
    sinonimos: ['dublin core', 'dc', 'metadados dublin core'],
    area: 'Metadados e Bibliotecas Digitais',
    moduloRelacionado: 'M2',
    conceitoCanonico: 'Conjunto padronizado de metadados simples criado em 1995 para descrição de recursos informacionais na Web. O Dublin Core Simples (DCMI) possui exatamente 15 elementos básicos não obrigatórios e repetíveis: Title, Creator, Subject, Description, Publisher, Contributor, Date, Type, Format, Identifier, Source, Language, Relation, Coverage, Rights.',
    armadilhaCebraspe: 'Afirmar que os elementos do Dublin Core possuem ordem hierárquica rígida ou que certos elementos são compulsórios. Todos os 15 elementos são facultativos e repetíveis.',
    aplicacaoCamara: 'O repositório digital da Câmara dos Deputados exporta seus metadados legislativos em Dublin Core via protocolo OAI-PMH para coleta pelo Google Acadêmico e redes internacionais.',
    fonteReferencia: 'DUBLIN CORE METADATA INITIATIVE. DCMI Metadata Terms. ISO 15836, 2020.',
  },

  // --- M3: CLASSIFICAÇÃO & INDEXAÇÃO ---
  {
    id: 'cddir',
    termo: 'Classificação Decimal de Direito (CDDir)',
    sinonimos: ['cddir', 'doris de queiroz carvalho', 'classificacao de direito'],
    area: 'Classificação Documentária',
    moduloRelacionado: 'M3',
    conceitoCanonico: 'Sistema de classificação bibliográfica especializada concebido na década de 1940 pela bibliotecária brasileira Doris de Queiroz Carvalho para suprir a ineficiência das tabelas universais (CDD/CDU) diante do sistema jurídico romano-germânico (Civil Law) brasileiro. Estrutura as classes jurídicas entre 340 e 349, com tabelas de divisões de forma.',
    armadilhaCebraspe: 'Dizer que a CDDir é uma tradução literal da classe 340 da CDD americana. Falso! É uma criação original brasileira adotada oficialmente pela Rede Virtual de Bibliotecas (RVBI) do Congresso Nacional.',
    aplicacaoCamara: 'A Biblioteca Pedro Aleixo classifica todos os seus livros jurídicos, doutrina e projetos de lei pela CDDir (ex.: 342 para Direito Constitucional e Administrativo; 341.2 para Direito Internacional Público).',
    fonteReferencia: 'CARVALHO, Doris de Queiroz. Classificação Decimal de Direito. Brasília: Senado Federal / RVBI, 2002.',
  },
  {
    id: 'notacao-autor-cutter',
    termo: 'Notação de Autor (Tabela Cutter-Sanborn e PHA)',
    sinonimos: ['cutter', 'cutter-sanborn', 'pha', 'notacao de autor', 'workmark'],
    area: 'Classificação e Tratamento Técnico',
    moduloRelacionado: 'M3',
    conceitoCanonico: 'Código alfanumérico que representa o sobrenome do autor (ou o título em entradas por título) para compor o número de chamada do livro na estante. A Tabela Cutter-Sanborn utiliza uma letra maiúscula seguida de números. A Tabela PHA foi criada no Brasil por Paulo Henrique de Assis para atender à frequência dos sobrenomes lusófonos (Silva, Santos, Oliveira).',
    armadilhaCebraspe: 'Regra da Workmark (marca de trabalho): é a letra minúscula (primeira letra do título, ignorando artigos) inserida após o número de Cutter para distinguir obras diferentes do mesmo autor. O Cebraspe diz que se usa letra maiúscula para a obra: ERRADO.',
    aplicacaoCamara: 'Um livro de José Afonso da Silva intitulado "Curso de Direito Constitucional Positivo" recebe na Biblioteca da Câmara a classificação 342, o Cutter S586 e a workmark "c" (342 S586c).',
    fonteReferencia: 'CUTTER, Charles Ammi. Cutter-Sanborn Three-Figure Author Table. Chicopee: HR Huntting, 1969.',
  },
  {
    id: 'linguagens-documentarias',
    termo: 'Linguagens Documentárias (Vocabulários Controlados)',
    sinonimos: ['linguagens documentarias', 'linguagem documentaria', 'vocabulario controlado', 'sistemas de organizacao do conhecimento', 'soc'],
    area: 'Linguagens Documentárias e Indexação',
    moduloRelacionado: 'M3',
    conceitoCanonico: 'Linguagens artificiais constituídas por vocabulário controlado e regras sintáticas/semânticas, concebidas para a indexação, armazenamento e recuperação temática da informação em sistemas documentários. Seu objetivo precípuo é neutralizar os ruídos da linguagem natural (sinonímia, polissemia e homonímia). Dividem-se em linguagens pré-coordenadas (sistemas de classificação CDD/CDU e cabeçalhos de assunto) e pós-coordenadas (unitermos e tesauros baseados em descritores combinados no momento da busca por operadores booleanos).',
    armadilhaCebraspe: 'Afirmar que a busca por palavras-chave em linguagem natural torna dispensável o uso de linguagens documentárias em bases especializadas. A ausência de vocabulário controlado causa perda severa de revocação (devido a sinônimos não buscados) e explosão de ruído (polissemia).',
    aplicacaoCamara: 'O Tesauro da Câmara dos Deputados e o Vocabulário Controlado Básico (VCB) da Rede RVBI padronizam os termos de indexação de projetos de lei, discursos e relatórios das comissões permanentes.',
    fonteReferencia: 'CINTRA, Anna Maria Marques et al. Para entender as linguagens documentárias. São Paulo: Polis, 2002.',
  },
  {
    id: 'indexacao-processo',
    termo: 'Indexação de Assuntos (Exaustividade, Especificidade & NBR 12676)',
    sinonimos: ['indexacao', 'processo de indexacao', 'exaustividade', 'especificidade', 'nbr 12676', 'politica de indexacao'],
    area: 'Tratamento Temático da Informação',
    moduloRelacionado: 'M3',
    conceitoCanonico: 'Processo intelectual de identificação e descrição do conteúdo temático de um documento mediante a atribuição de termos representativos de uma linguagem documentária (NBR 12676 / ISO 5963). Compreende três etapas canônicas: (1) Exame e leitura técnica do documento; (2) Identificação dos conceitos centrais; (3) Tradução dos conceitos para os termos autorizados da linguagem. A Exaustividade corresponde ao número total de conceitos atribuídos (alta exaustividade maximiza a revocação). A Especificidade é o grau de precisão do termo em relação ao conceito abordado (alta especificidade maximiza a precisão).',
    armadilhaCebraspe: 'Inversão das relações de recuperação: a banca costuma afirmar que alta especificidade aumenta a revocação e alta exaustividade aumenta a precisão. Falso! Exaustividade eleva a revocação (traz mais documentos); especificidade eleva a precisão (traz documentos mais pertinentes).',
    aplicacaoCamara: 'Ao indexar uma Proposta de Emenda à Constituição (PEC) sobre Reforma Tributária, o bibliotecário aplica alta especificidade para permitir que a consultoria legislativa localize a proposta sem ruídos irrelevantes.',
    fonteReferencia: 'ABNT. NBR 12676: Métodos para análise de documentos, determinação de seus assuntos e seleção de termos de indexação. Rio de Janeiro, 1992.',
  },
  {
    id: 'tesauros-relacoes',
    termo: 'Relações em Tesauros (TG, TE, TA, USE, UP)',
    sinonimos: ['tesauro', 'tesauros', 'relacoes tesauro', 'relacoes em tesauros', 'termo geral', 'termo especifico', 'termo associado', 'use', 'up'],
    area: 'Linguagens Documentárias e Indexação',
    moduloRelacionado: 'M3',
    conceitoCanonico: 'Vocabulário controlado de termos dinâmicos inter-relacionados semanticamente. Possui três tipos canônicos de relações: (1) Relação de Equivalência (sinonímia/quase-sinonímia: USE para termo preferido e UP/Usado Para para termo não preferido); (2) Relação Hierárquica (gênero/espécie ou todo/parte: TG - Termo Geral / BT e TE - Termo Específico / NT); (3) Relação Associativa (afinidade conceitual ou causalidade: TA - Termo Associado / RT).',
    armadilhaCebraspe: 'Inversão das relações (ex.: afirmar que USE indica o termo proibido e UP o preferido, ou classificar uma relação todo/parte como associativa).',
    aplicacaoCamara: 'O Vocabulário Controlado da Câmara dos Deputados e o Tesauro do Senado orientam os analistas a indexarem proposições legislativas com termos autorizados.',
    fonteReferencia: 'ISO 25964-1. Information and documentation - Thesauri and interoperability with other vocabularies. Genebra: ISO, 2011.',
  },

  // --- M4: RECUPERAÇÃO DA INFORMAÇÃO & FONTES ---
  {
    id: 'urn-lexml',
    termo: 'URN LexML (Identificador Persistente)',
    sinonimos: ['urn lexml', 'lexml', 'urn lex', 'lexml brasil'],
    area: 'Fontes de Informação Jurídica e SRI',
    moduloRelacionado: 'M4',
    conceitoCanonico: 'Identificador unívoco e persistente baseado no padrão URN (Uniform Resource Name / RFC 2141) adotado pelo Portal LexML Brasil para nomear atos normativos, proposições, jurisprudência e doutrina de todas as esferas federativas, com a sintaxe estruturada: urn:lex:país:autoridade:tipo_documento:data;número.',
    armadilhaCebraspe: 'Afirmar que o LexML utiliza URLs comuns da internet suscetíveis a erros de página não encontrada (link quebrado / erro 404). A URN é independente da localização física do arquivo.',
    aplicacaoCamara: 'A Lei nº 8.112/1990 possui o identificador permanente: urn:lex:br:federal:lei:1990-12-11;8112, permitindo que cidadãos e deputados acessem o texto fidedigno diretamente.',
    fonteReferencia: 'LIMA, João Alberto de Oliveira; PASSOS, Edilenice. LexML – visão unificada da informação legislativa e jurídica do Brasil. 2019.',
  },
  {
    id: 'revocacao-vs-precisao',
    termo: 'Revocação (Recall) vs. Precisão (Precision)',
    sinonimos: ['revocacao', 'precisao', 'recall', 'precision', 'metricas de recuperacao'],
    area: 'Sistemas de Recuperação da Informação (SRI)',
    moduloRelacionado: 'M4',
    conceitoCanonico: 'As duas métricas clássicas de eficácia de um SRI formuladas nos testes de Cranfield (Cleverdon). Revocação é a proporção de documentos relevantes recuperados em relação ao total de relevantes existentes na base. Precisão é a proporção de documentos relevantes recuperados em relação ao total de documentos trazidos pela busca. Apresentam relação inversamente proporcional.',
    armadilhaCebraspe: 'A banca diz que uma busca perfeita em bases imensas maximiza simultaneamente a 100% a revocação e a precisão com operadores booleanos simples. Falso, o aumento de um costuma gerar a queda do outro.',
    aplicacaoCamara: 'Em uma consultoria técnica para relatoria de PEC, o analista bibliotecário prioriza alta revocação (varrer tudo o que existe sobre a matéria, tolerando alguns ruídos).',
    fonteReferencia: 'LANCASTER, F. Wilfrid. Avaliação da eficácia dos sistemas de recuperação da informação. Brasília: Briquet de Lemos, 2004.',
  },
  {
    id: 'secoes-dou',
    termo: 'Três Seções do Diário Oficial da União (DOU)',
    sinonimos: ['secoes dou', 'dou secao 1 2 3', 'diario oficial da uniao'],
    area: 'Fontes de Informação Governamental',
    moduloRelacionado: 'M4',
    conceitoCanonico: 'Divisão tripartite dos atos da Administração Pública Federal editados pela Imprensa Nacional: Seção 1 (Atos normativos gerais: leis, decretos, medidas provisórias, portarias normativas); Seção 2 (Atos de recursos humanos: nomeação, posse, exoneração e aposentadoria); Seção 3 (Contratos, convênios, editais de licitação, concursos públicos e avisos ineditoriais).',
    armadilhaCebraspe: 'A casca de banana clássica do Cebraspe é inverter as Seções 2 e 3 (afirmar que editais de concurso saem na Seção 2 ou que nomeações de servidores saem na Seção 3).',
    aplicacaoCamara: 'A convocação e nomeação dos aprovados no concurso da Câmara dos Deputados é publicada na Seção 2 do DOU; a lei orgânica promulgada é publicada na Seção 1.',
    fonteReferencia: 'BRASIL. Imprensa Nacional. Decreto nº 9.215, de 29 de novembro de 2017.',
  },
  {
    id: 'disseminacao-seletiva-informacao',
    termo: 'Disseminação Seletiva da Informação (DSI / SDI)',
    sinonimos: ['dsi', 'sdi', 'disseminacao seletiva', 'disseminacao seletiva da informacao', 'alerta informacional'],
    area: 'Serviço de Referência e Produtos Informacionais',
    moduloRelacionado: 'M4',
    conceitoCanonico: 'Serviço proativo e automatizado de alerta concebido por Hans Peter Luhn (IBM, 1958) que visa fornecer periodicamente a cada pesquisador, tomador de decisão ou grupo parlamentar apenas os novos documentos e publicações que correspondam ao seu perfil pré-definido de interesses (profile). Opera mediante a comparação sistemática entre os descritores dos novos itens entrados na base e a matriz de tópicos de interesse cadastrada.',
    armadilhaCebraspe: 'Confundir DSI com boletim informativo genérico ou newsletter distribuída indistintamente a todos os usuários. A DSI caracteriza-se obrigatoriamente pela personalização estrita baseada no perfil individual cadastrado.',
    aplicacaoCamara: 'Consultores legislativos e relatores de comissões temáticas recebem alertas diários automáticos de DSI com proposições, jurisprudência e doutrina pertinentes aos projetos sob sua relatoria.',
    fonteReferencia: 'LUHN, Hans Peter. A Business Intelligence System. IBM Journal of Research and Development, 1958.',
  },
  {
    id: 'servico-de-referencia',
    termo: 'Serviço de Referência e Entrevista de Referência (Grogan)',
    sinonimos: ['servico de referencia', 'entrevista de referencia', 'grogan', 'processo de referencia'],
    area: 'Serviço de Referência e Atendimento ao Usuário',
    moduloRelacionado: 'M4',
    conceitoCanonico: 'Atendimento direto, pessoal e interativo prestado pelo bibliotecário ao consulente para solucionar suas necessidades de informação. Denis Grogan sistematizou o processo de referência em oito estágios sucessivos, desde a necessidade de informação latente e não expressa (necessidade visceral), passando pela necessidade consciente e formalizada, até a questão apresentada ao bibliotecário. A Entrevista de Referência é o diálogo profissional estruturado em perguntas abertas para esclarecer a real demanda subjacente à consulta.',
    armadilhaCebraspe: 'Afirmar que na entrevista de referência o bibliotecário deve usar prioritariamente perguntas fechadas (que induzem sim/não) para agilizar o atendimento. Grogan preconiza perguntas abertas e escuta atenta para revelar a necessidade informacional real.',
    aplicacaoCamara: 'No balcão de atendimento ou no serviço de referência virtual da Biblioteca Pedro Aleixo, os analistas realizam a entrevista de referência para delimitar com precisão o escopo doutrinário demandado pelos parlamentares.',
    fonteReferencia: 'GROGAN, Denis. A prática do serviço de referência. Brasília: Briquet de Lemos, 1995/2001.',
  },

  // --- M5: GESTÃO & DESENVOLVIMENTO DE COLEÇÕES ---
  {
    id: 'desbastamento-vs-descarte',
    termo: 'Desbastamento vs. Descarte de Coleções (Vergueiro)',
    sinonimos: ['desbastamento', 'descarte', 'desbaste', 'vergueiro'],
    area: 'Gestão de Unidades de Informação e Coleções',
    moduloRelacionado: 'M5',
    conceitoCanonico: 'Etapas distintas da política de desenvolvimento de coleções (Waldomiro Vergueiro). O Desbastamento (ou desbaste) é a retirada de documentos de uso pouco frequente do acervo principal para armazenamento secundário (depósito de reserva), mantendo a obra sob a custódia da biblioteca. O Descarte é a eliminação física definitiva da obra do acervo (por alienação, doação, permuta ou destruição/reciclagem).',
    armadilhaCebraspe: 'Tratar desbastamento e descarte como sinônimos perfeitos. Desbastar NÃO é destruir nem jogar fora; é remanejar fisicamente para otimizar o espaço das estantes abertas.',
    aplicacaoCamara: 'Diários de sessões de décadas passadas são desbastados para o depósito subterrâneo da Câmara, enquanto obras totalmente danificadas sem valor histórico passam pelo processo formal de descarte.',
    fonteReferencia: 'VERGUEIRO, Waldomiro. Desenvolvimento de Coleções. São Paulo: Polis / APB, 1989.',
  },
  {
    id: 'modelo-seci-conhecimento',
    termo: 'Modelo SECI de Criação do Conhecimento (Nonaka & Takeuchi)',
    sinonimos: ['modelo seci', 'nonaka takeuchi', 'socializacao externalizacao combinacao internalizacao'],
    area: 'Gestão da Informação e do Conhecimento',
    moduloRelacionado: 'M5',
    conceitoCanonico: 'Espiral contínua de conversão do conhecimento formulada por Ikujiro Nonaka e Hirotaka Takeuchi (1995): (1) Socialização (Tácito para Tácito - compartilhamento de experiências práticas e modelos mentais); (2) Externalização (Tácito para Explícito - articulação do saber em conceitos, metáforas e manuais escritos); (3) Combinação (Explícito para Explícito - sistematização de documentos e bases de dados); (4) Internalização (Explícito para Tácito - aprendizado prático vivenciado / learning by doing).',
    armadilhaCebraspe: 'Inversão das fases (ex.: afirmar que Externalização é de explícito para explícito ou que o conhecimento tácito é facilmente transferível sem interação interpessoal).',
    aplicacaoCamara: 'Quando um consultor legislativo sênior redige um manual de técnica legislativa a partir de sua vivência tácita, ocorre a fase de Externalização.',
    fonteReferencia: 'NONAKA, Ikujiro; TAKEUCHI, Hirotaka. The Knowledge-Creating Company. Oxford University Press, 1995.',
  },
  {
    id: 'estudo-de-usuarios',
    termo: 'Estudo de Usuários e Comportamento Informacional',
    sinonimos: ['estudo de usuarios', 'comportamento informacional', 'necessidades de informacao', 'sense-making', 'dervin', 'kuhlthau'],
    area: 'Usuários da Informação e Gestão de Serviços',
    moduloRelacionado: 'M5',
    conceitoCanonico: 'Investigação sistemática e contínua que emprega métodos qualitativos e quantitativos para identificar hábitos, necessidades conscientes ou inconscientes, fluxos e barreiras no uso da informação por uma comunidade. Evoluiu da abordagem tradicional voltada ao sistema (orientada a estatísticas quantitativas de empréstimo e uso da coleção) para a abordagem alternativa voltada ao usuário (orientada aos processos cognitivos, situacionais e afetivos de busca e construção de sentido, com destaque para o modelo Sense-Making de Brenda Dervin e o Information Search Process de Carol Kuhlthau).',
    armadilhaCebraspe: 'Reduzir estudos de usuários a relatórios estatísticos de balcão e circulação de livros. O Cebraspe enfatiza a abordagem construtivista e fenomenológica focada no contexto e na lacuna de sentido (gaps) do indivíduo.',
    aplicacaoCamara: 'Pesquisas periódicas de demanda diagnóstica aplicadas às consultorias parlamentares para subsidiar a aquisição de bases jurídicas e a modelagem do catálogo da Câmara.',
    fonteReferencia: 'FIGUEIREDO, Nice Menezes de. Metodologias para promoção do uso da informação. São Paulo: Nobel / APB, 1991.',
  },

  // --- M6: BIBLIOTECAS DIGITAIS, PRESERVAÇÃO & IA ---
  {
    id: 'modelo-oais',
    termo: 'Modelo de Referência OAIS (ISO 14721)',
    sinonimos: ['oais', 'open archival information system', 'iso 14721', 'sip aip dip'],
    area: 'Preservação Digital e Repositórios',
    moduloRelacionado: 'M6',
    conceitoCanonico: 'O Open Archival Information System (ISO 14721) é um modelo conceitual internacional de referência que padroniza os processos de preservação digital de longo prazo em Repositórios Digitais Confiáveis (RDC-Arq). Estrutura o ciclo informacional em três pacotes: SIP (Submission Information Package), AIP (Archival Information Package) e DIP (Dissemination Information Package).',
    armadilhaCebraspe: 'Afirmar que o OAIS é um software pronto instalável (como o DSpace) ou uma ferramenta de backup. O OAIS é um modelo conceitual/arquitetural, não um software específico.',
    aplicacaoCamara: 'O repositório de documentos históricos digitais da Câmara dos Deputados custodia o pacote AIP com checagem de hashes SHA-256 e entrega ao cidadão o pacote DIP leve em PDF.',
    fonteReferencia: 'ISO. ISO 14721: Space data and information transfer systems — Open archival information system (OAIS) — Reference model, 2012/2025.',
  },
  {
    id: 'emulacao-vs-migracao',
    termo: 'Emulação vs. Migração de Formatos',
    sinonimos: ['emulacao', 'migracao digital', 'estrategias de preservacao digital'],
    area: 'Preservação Digital',
    moduloRelacionado: 'M6',
    conceitoCanonico: 'Estratégias centrais para combater a obsolescência lógica dos formatos digitais. A Migração converte periodicamente o arquivo digital de um formato em desuso para um formato mais novo (altera os bits do arquivo). A Emulação mantém o arquivo binário original estritamente intocado e recria o ambiente de hardware/software antigo por meio de um programa emulador em computadores modernos.',
    armadilhaCebraspe: 'Dizer que a emulação altera o código binário original da obra digital para adequá-lo à nova máquina. O que preserva os bits originais intocados é a emulação.',
    aplicacaoCamara: 'Arquivos de gravações históricas de discursos dos anos 1990 salvos em formatos proprietários extintos podem ser executados por emuladores de sistemas operacionais da época.',
    fonteReferencia: 'ARELLANO, Miguel Ángel Márdero. Critérios para a preservação digital da informação científica. Brasília: UnB, 2008.',
  },
  {
    id: 'ndsa-levels-preservation',
    termo: 'Níveis de Preservação da NDSA (Levels of Preservation - LoP)',
    sinonimos: ['ndsa', 'levels of preservation', 'lop', 'niveis de preservacao'],
    area: 'Preservação Digital e Repositórios Confiáveis',
    moduloRelacionado: 'M6',
    conceitoCanonico: 'Guia prático de maturidade e confiabilidade desenvolvido pela National Digital Stewardship Alliance (NDSA) que avalia intervenções de preservação digital em 5 áreas vitais: Armazenamento/Localização geográfica, Fixidez de integridade (checksums), Segurança da informação, Metadados e Formatos de arquivo, escalonados em 4 níveis progressivos.',
    armadilhaCebraspe: 'Supor que a mera realização de cópias de segurança (backups simples) atinge os níveis avançados de preservação. O backup não garante monitoramento de fixidez nem obsolescência lógica.',
    aplicacaoCamara: 'O plano de preservação digital da Câmara dos Deputados adota auditoria criptográfica automatizada para assegurar que nenhum pronunciamento parlamentar gravado seja corrompido.',
    fonteReferencia: 'NDSA. Levels of Digital Preservation. National Digital Stewardship Alliance, 2019/2020.',
  },

  // --- M7: PRESERVAÇÃO FÍSICA & CONSERVAÇÃO ---
  {
    id: 'principio-reversibilidade',
    termo: 'Princípio da Reversibilidade na Restauração',
    sinonimos: ['reversibilidade', 'principio da reversibilidade', 'restauracao de documentos'],
    area: 'Preservação, Conservação e Restauração',
    moduloRelacionado: 'M7',
    conceitoCanonico: 'Postulado ético supremo da restauração de acervos documentais: qualquer intervenção curativa ou química aplicada a uma obra rara ou documento histórico deve poder ser desfeita no futuro sem causar danos físicos ao suporte original, caso surjam tecnologias ou produtos mais avançados.',
    armadilhaCebraspe: 'Dizer que o uso de fitas adesivas comerciais transparentes (tipo durex) é aceitável em pequenos rasgos de livros raros. É terminantemente proibido devido à irreversibilidade da cola e acidez do plástico.',
    aplicacaoCamara: 'O laboratório de conservação e restauração da Câmara dos Deputados utiliza exclusivamente enxertos de papel japonês (kozo) colados com metilcelulose ou CMC hidrossolúvel reversível na recuperação de constituições originais.',
    fonteReferencia: 'SPINELLI JÚNIOR, Jayme. A conservação de acervos bibliográficos e documentais. Rio de Janeiro: Fundação Biblioteca Nacional, 1997.',
  },
  {
    id: 'lignina-e-acidez',
    termo: 'Lignina e Hidrólise Ácida do Papel',
    sinonimos: ['lignina', 'hidrolise acida', 'papel acido', 'acidez do papel'],
    area: 'Preservação e Degradação de Suportes',
    moduloRelacionado: 'M7',
    conceitoCanonico: 'A lignina é um polímero complexo presente na madeira. Papéis fabricados industrialmente a partir de pasta mecânica de madeira contêm alto teor de lignina, que sob a ação da luz e do oxigênio sofre oxidação, gerando compostos ácidos. A hidrólise ácida resultante rompe as cadeias de celulose, tornando o papel amarelado e quebradiço (friável).',
    armadilhaCebraspe: 'Afirmar que papéis antigos de trapos de algodão anteriores ao século XIX são mais ácidos do que papéis de jornal do século XX. O papel de trapo é alcalino/neutro e muito mais durável que o papel mecânico moderno.',
    aplicacaoCamara: 'Obras do acervo da Câmara impressas na primeira metade do século XX passam por processos de desacidificação de massa e armazenamento em invólucros neutros com reserva alcalina de CaCO3.',
    fonteReferencia: 'BECK, Ingrid. Manual de Conservação e Preservação de Documentos de Papel. Rio de Janeiro: Arquivo Nacional, 1985.',
  },

  // --- M8: NORMALIZAÇÃO DOCUMENTAL (ABNT) ---
  {
    id: 'abnt-10520-2023-caixa-baixa',
    termo: 'Nova ABNT NBR 10520:2023 (Fim da Caixa Alta)',
    sinonimos: ['nbr 10520 2023', 'citacao abnt 2023', 'fim da caixa alta citacao'],
    area: 'Normalização Documental',
    moduloRelacionado: 'M8',
    conceitoCanonico: 'Histórica revisão da ABNT NBR 10520 publicada em julho de 2023 que extinguiu a obrigatoriedade do uso de letras maiúsculas (caixa alta) para sobrenomes de autores entre parênteses. A chamada autor-data agora é grafada em letras maiúsculas e minúsculas TANTO fora QUANTO DENTRO dos parênteses: (Silva, 2023, p. 10) e não mais (SILVA, 2023, p. 10).',
    armadilhaCebraspe: 'Itens em provas recentes tentando validar como única forma correta a grafia em caixa alta dentro dos parênteses "(SOUZA, 2024)". No padrão NBR 10520:2023, a grafia correta é "(Souza, 2024)".',
    aplicacaoCamara: 'Os pareceres técnicos da Consultoria Legislativa e as publicações das Edições Câmara adotam rigorosamente a nova NBR 10520:2023 em suas referências de citações.',
    fonteReferencia: 'ABNT. NBR 10520: Informação e documentação — Citações em documentos — Apresentação. Rio de Janeiro: ABNT, 2023.',
  },
  {
    id: 'citacao-longa-abnt',
    termo: 'Citação Direta Longa (ABNT NBR 10520:2023)',
    sinonimos: ['citacao direta longa', 'recuo 4cm', 'citacao mais de 3 linhas'],
    area: 'Normalização Documental',
    moduloRelacionado: 'M8',
    conceitoCanonico: 'Transcrição literal de texto original com mais de três linhas de extensão. Deve obrigatoriamente ser apresentada em parágrafo isolado próprio, com recuo uniforme de exatamente 4 cm a partir da margem esquerda, fonte menor do que a do texto (corpo 10), espaçamento interlinear simples e SEM ASPAS DUPLAS NEM SIMPLES.',
    armadilhaCebraspe: 'A banca afirma que a citação direta com recuo de 4 cm deve ser colocada entre aspas duplas. É terminantemente proibido o uso de aspas no bloco recuado.',
    aplicacaoCamara: 'Transcrições integrais de votos de relatores ou acórdãos de tribunais inseridos em notas técnicas parlamentares seguem o recuo obrigatório de 4 cm.',
    fonteReferencia: 'ABNT. NBR 10520:2023, cláusula 5.2.',
  },

  // --- M9: COMUNICAÇÃO CIENTÍFICA & MÉTRICAS ---
  {
    id: 'lei-de-bradford',
    termo: 'Lei de Bradford (Dispersão de Periódicos)',
    sinonimos: ['lei de bradford', 'bradford', 'dispersao de periodicos', 'zonas de bradford'],
    area: 'Estudos Métricos da Informação (Bibliometria)',
    moduloRelacionado: 'M9',
    conceitoCanonico: 'Lei bibliométrica formulada por Samuel C. Bradford em 1934 que estabelece que, se periódicos científicos forem ordenados em ordem decrescente de produtividade de artigos sobre determinado assunto, eles podem ser divididos em um núcleo central de revistas mais produtivas e zonas sucessivas contendo o mesmo número de artigos, onde a quantidade de periódicos cresce geometricamente na proporção 1 : n : n².',
    armadilhaCebraspe: 'Inverter a proporção dizendo que a quantidade de artigos cresce geometricamente e os periódicos mantêm-se constantes, ou confundir a lei de Bradford (periódicos) com a de Lotka (autores) ou de Zipf (palavras).',
    aplicacaoCamara: 'A Biblioteca da Câmara utiliza a Lei de Bradford para assinar os periódicos essenciais do núcleo de Direito e Ciência Política, evitando gastos desnecessários com revistas dispersas de baixa relevância.',
    fonteReferencia: 'BRADFORD, Samuel C. Sources of Information on Specific Subjects. Engineering, 1934.',
  },
  {
    id: 'principios-fair',
    termo: 'Princípios FAIR para Gestão de Dados',
    sinonimos: ['fair', 'principios fair', 'dados fair', 'findable accessible interoperable reusable'],
    area: 'Comunicação Científica e Ciência Aberta',
    moduloRelacionado: 'M9',
    conceitoCanonico: 'Conjunto de diretrizes internacionais (Wilkinson et al., 2016) para garantir a governança e reuso de dados de pesquisa na era da Ciência Aberta: Findable (Localizáveis com identificadores persistentes e metadados ricos), Accessible (Acessíveis por protocolos abertos e gratuitos), Interoperable (Interoperáveis mediante vocabulários controlados formais) e Reusable (Reutilizáveis com licenças claras de uso como Creative Commons).',
    armadilhaCebraspe: 'Afirmar que FAIR significa que todos os dados devem ser públicos e sem qualquer restrição de segurança. Dados podem ser FAIR mesmo sob controle de acesso justificado por sigilo legal (tão aberto quanto possível, tão fechado quanto necessário).',
    aplicacaoCamara: 'O portal de Dados Abertos da Câmara dos Deputados disponibiliza as votações e tramitações em formatos FAIR (JSON, XML e CSV com URIs persistentes).',
    fonteReferencia: 'WILKINSON, M. et al. The FAIR Guiding Principles for scientific data management and stewardship. Scientific Data, 2016.',
  },

  // --- M10: LEGISLAÇÃO & CONTEXTO LEGISLATIVO ---
  {
    id: 'lei-14837-2024',
    termo: 'Lei nº 14.837/2024 (Sistema Nacional de Bibliotecas Escolares)',
    sinonimos: ['lei 14837', 'lei 14.837', 'lei bibliotecas escolares 2024', 'snbe'],
    area: 'Legislação e Políticas de Bibliotecas',
    moduloRelacionado: 'M10',
    conceitoCanonico: 'Legislação federal sancionada em abril de 2024 que alterou a Lei nº 12.244/2010. Instituiu formalmente o Sistema Nacional de Bibliotecas Escolares (SNBE), redefiniu a biblioteca escolar como espaço obrigatório de incentivo ao letramento e leitura com tecnologias assistivas, e reafirmou expressamente a obrigatoriedade da atuação de profissional Bibliotecário devidamente registrado no Conselho Regional de Biblioteconomia (CRB) em todas as escolas públicas e privadas.',
    armadilhaCebraspe: 'Questões afirmando que qualquer professor readaptado ou funcionário administrativo pode substituir o bibliotecário na gestão técnica da biblioteca escolar. A nova legislação reafirmou a exigência de bacharel em Biblioteconomia com registro no CRB.',
    aplicacaoCamara: 'A tramitação do projeto que originou a Lei 14.837/2024 passou pelas comissões de Educação e de Constituição e Justiça da Câmara dos Deputados, com pareceres instruídos pelo acervo da Casa.',
    fonteReferencia: 'BRASIL. Lei nº 14.837, de 9 de abril de 2024. Altera a Lei nº 12.244, de 24 de maio de 2010.',
  },
  {
    id: 'lai-graus-sigilo',
    termo: 'Prazos e Graus de Sigilo da LAI (Lei nº 12.527/2011)',
    sinonimos: ['lai', 'graus de sigilo lai', 'ultrassecreto secreto reservado', 'prazos lai'],
    area: 'Legislação Federal e Gestão Documental',
    moduloRelacionado: 'M10',
    conceitoCanonico: 'A Lei de Acesso à Informação (LAI) classifica os documentos sigilosos em três graus estritos: (1) Ultrassecreto: prazo máximo de sigilo de 25 anos; (2) Secreto: prazo máximo de 15 anos; (3) Reservado: prazo máximo de 5 anos. Prazo de resposta a pedidos de informação: imediato ou em até 20 dias, prorrogáveis por mais 10 dias mediante justificativa expressa.',
    armadilhaCebraspe: 'Inverter os prazos (ex.: afirmar que reservado dura 15 anos e ultrassecreto 30 anos) ou dizer que informações sobre violação de direitos humanos podem ser mantidas sob sigilo (são públicas e não podem ser restritas).',
    aplicacaoCamara: 'O Serviço de Informação ao Cidadão (SIC) da Câmara dos Deputados responde a requerimentos de cidadãos dentro do prazo estrito de 20 + 10 dias da LAI.',
    fonteReferencia: 'BRASIL. Lei nº 12.527, de 18 de novembro de 2011 (Lei de Acesso à Informação).',
  },

  // --- M11 & M12: CONHECIMENTOS BÁSICOS ---
  {
    id: 'regra-mane-negacao',
    termo: 'Regra MANÉ (Negação da Condicional P → Q)',
    sinonimos: ['regra mane', 'negacao da condicional', 'negar condicional'],
    area: 'Raciocínio Lógico-Matemático (RLM)',
    moduloRelacionado: 'M11',
    conceitoCanonico: 'Mnemônico canônico de RLM para a negação lógica da proposição condicional (P → Q): MANTÉM a primeira parte E NEGA a segunda parte (¬(P → Q) ≡ P ∧ ¬Q). A negação de uma condicional resulta SEMPRE em uma CONJUNÇÃO, e nunca em outra condicional.',
    armadilhaCebraspe: 'A banca tenta fazer o candidato negar uma condicional usando outra condicional (ex.: "Se não chover, então vou à praia" para negar "Se chover, então não vou à praia": ERRADO!).',
    aplicacaoCamara: 'Sentença da Câmara: "Se o projeto for votado hoje, então a sessão será encerrada". Negação correta: "O projeto foi votado hoje E a sessão NÃO foi encerrada".',
    fonteReferencia: 'ALENCAR FILHO, Edgard de. Iniciação à Lógica Matemática. São Paulo: Nobel, 2002.',
  },
  {
    id: 'skimming-e-scanning',
    termo: 'Técnicas de Skimming e Scanning (Inglês Instrumental)',
    sinonimos: ['skimming', 'scanning', 'leitura instrumental'],
    area: 'Língua Inglesa Instrumental',
    moduloRelacionado: 'M12',
    conceitoCanonico: 'Estratégias centrais de leitura rápida e eficiente. Skimming é a leitura superficial e panorâmica para captar a ideia central, o tom e a macroestrutura do texto sem se apegar a detalhes. Scanning é a varredura visual rápida com os olhos buscando uma informação pontual específica (como uma data, número, nome próprio ou termo do enunciado da questão).',
    armadilhaCebraspe: 'Inverter as funções: dizer que o scanning busca o sentido global do texto e o skimming busca números e palavras-chave isoladas.',
    aplicacaoCamara: 'Ao consultar relatórios da Library of Congress ou tratados internacionais em inglês, o analista faz skimming para triagem e scanning para localizar o artigo específico requerido pelo deputado.',
    fonteReferencia: 'NUTTALL, Christine. Teaching Reading Skills in a Foreign Language. Oxford: Heinemann, 1996.',
  },
];
